### ISSUE TITLE
Pending TODO's

### ISSUE THREAD

**Issue by BrianJVarley** [BrianJVarley/react-native-prototyping#3]
- [ ] Fix SquareOffsetState.spec
- [ ] Fix circle.yml config for builds
- [ ] Add swipe view to diagram image overlay
- [ ] Add extra measurement diagrams detailing cut sequence.
- [ ] Add extra measurement diagrams detailing cut sequence.
- [x] Edit image assets to @ screen sizes and remove white line
